server:
  port: 8080
  readTimeout: 10
  writeTimeout: 10
  host: "0.0.0.0"

database:
  influxURL: "http://localhost:8086"
  influxOrg: "analytics"
  influxBucket: "metrics"
  # Token should be set through environment variable DATABASE_INFLUXTOKEN
  # Password should be set through environment variable DATABASE_INFLUXPASSWORD

redis:
  host: "localhost"
  port: 6379
  # Password should be set through environment variable REDIS_PASSWORD
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  topic: "analytics"
  groupID: "analytics-group"

logging:
  level: "info"
  file: "logs/analytics.log"

jwt:
  # Secret should be set through environment variable JWT_SECRET
  expireMins: 60